"""empty message

Revision ID: 182ae11ab5f1
Revises: 
Create Date: 2024-03-17 14:18:29.181705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182ae11ab5f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('numBedrooms', sa.String(length=80), nullable=True),
    sa.Column('numBathrooms', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('types', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
